 Test generated by RoostGPT for test EmojiSearch using AI Type Open AI and AI Model gpt-4

import React, { PureComponent } from "react"
import { shallow } from "enzyme"
import PropTypes from "prop-types"
import SearchInput from "./SearchInput"

describe("SearchInput Component", () => {
  let component;

  beforeEach(() => {
    component = shallow(<SearchInput />);
  });

  test("It should render without errors", () => {
    expect(component.exists()).toBe(true);
  });

  test("It should have an input field", () => {
    expect(component.find('input[type="text"]').length).toBe(1);
  });

  test("It should change state on input change", () => {
    const input = component.find('input[type="text"]');
    input.simulate('change', { target: { value: 'test' } });
    expect(component.state().value).toEqual('test');
  });

  test("It should call props.onChange when input changes", () => {
    const mockOnChange = jest.fn();
    component.setProps({ onChange: mockOnChange });
    const input = component.find('input[type="text"]');
    input.simulate('change', { target: { value: 'test' } });
    expect(mockOnChange).toHaveBeenCalledWith('test');
  });

  afterEach(() => {
    jest.clearAllMocks();
  });
});
