 Test generated by RoostGPT for test EmojiSearch using AI Type Open AI and AI Model gpt-4

import { filterEmoji } from "./filterEmoji";
import emojiList from "./emojiList.json";

describe("Testing filterEmoji function", () => {
  let testEmojiList;

  beforeEach(() => {
    testEmojiList = [...emojiList];
  });

  test("Should return an emoji list based on search keyword", () => {
    const result = filterEmoji(testEmojiList, "happy", 20);
    expect(result).toEqual(
      expect.arrayContaining([
        expect.objectContaining({
          title: expect.stringContaining("happy"),
        }),
      ])
    );
  });

  test("Should return an empty array when no match is found", () => {
    const result = filterEmoji(testEmojiList, "nonExistingEmoji", 20);
    expect(result).toEqual([]);
  });

  test("Should limit the number of results based on the maxResults parameter", () => {
    const result = filterEmoji(testEmojiList, "face", 5);
    expect(result.length).toBe(5);
  });

  test("Should handle case sensitivity", () => {
    const result = filterEmoji(testEmojiList, "Happy", 20);
    expect(result).toEqual(
      expect.arrayContaining([
        expect.objectContaining({
          title: expect.stringContaining("happy"),
        }),
      ])
    );
  });

  test("Should return an empty array when keyword is an empty string", () => {
    const result = filterEmoji(testEmojiList, "", 20);
    expect(result).toEqual([]);
  });
});
