 Test generated by RoostGPT for test EmojiSearch using AI Type Open AI and AI Model gpt-4

import React from 'react';
import { render, unmountComponentAtNode } from 'react-dom';
import { shallow } from 'enzyme';
import EmojiResultRow from './EmojiResultRow';

let container = null;

beforeAll(() => {
  container = document.createElement('div');
  document.body.appendChild(container);
});

afterAll(() => {
  unmountComponentAtNode(container);
  container.remove();
  container = null;
});

describe('EmojiResultRow', () => {
  test('renders without crashing', () => {
    render(<EmojiResultRow />, container);
  });

  test('has a valid prop type', () => {
    const emoji = {
      title: 'Grinning',
      symbol: '😀',
      keywords: 'grinning face happy smiley emotion emotion'
    };
    const wrapper = shallow(<EmojiResultRow {...emoji} />);
    expect(wrapper.instance().props.title).toBe('Grinning');
    expect(wrapper.instance().props.symbol).toBe('😀');
    expect(wrapper.instance().props.keywords).toBe('grinning face happy smiley emotion emotion');
  });

  test('throws an error when prop type is invalid', () => {
    const consoleSpy = jest.spyOn(console, 'error');

    const emoji = {
      title: 'Grinning',
      symbol: '😀',
      keywords: 123 // invalid prop type
    };

    expect(() => {
      shallow(<EmojiResultRow {...emoji} />);
    }).toThrow();

    expect(consoleSpy).toHaveBeenCalled();
    consoleSpy.mockRestore();
  });
});
