 Test generated by RoostGPT for test EmojiSearch using AI Type Open AI and AI Model gpt-4

import React from "react";
import { render, cleanup } from "@testing-library/react";
import EmojiResultRow from "./EmojiResultRow";

describe("EmojiResultRow", () => {
  afterEach(cleanup);

  test("renders without crashing", () => {
    render(<EmojiResultRow />);
  });

  test("displays the correct emoji", () => {
    const { getByTestId } = render(<EmojiResultRow symbol="😀" title="Grinning Face" />);
    expect(getByTestId("emoji-symbol")).toHaveTextContent("😀");
  });

  test("displays the correct title", () => {
    const { getByTestId } = render(<EmojiResultRow symbol="😀" title="Grinning Face" />);
    expect(getByTestId("emoji-title")).toHaveTextContent("Grinning Face");
  });
});
