 Test generated by RoostGPT for test EmojiSearch using AI Type Open AI and AI Model gpt-4

import React from 'react';
import { shallow } from 'enzyme';
import App from './App';
import Header from "./Header"
import SearchInput from "./SearchInput"
import EmojiResults from "./EmojiResults"
import filterEmoji from "./filterEmoji"

describe('App component', () => {
  let wrapper;
  beforeEach(() => {
    wrapper = shallow(<App />);
  });

  test('renders without crashing', () => {
    expect(wrapper.exists()).toBe(true);
  });

  test('renders Header component', () => {
    expect(wrapper.find(Header).length).toBe(1);
  });

  test('renders SearchInput component', () => {
    expect(wrapper.find(SearchInput).length).toBe(1);
  });

  test('renders EmojiResults component', () => {
    expect(wrapper.find(EmojiResults).length).toBe(1);
  });

  test('filterEmoji function is called on SearchInput change', () => {
    const spy = jest.spyOn(filterEmoji, 'default');
    const event = {
      target: { value: 'smile' },
    };
    wrapper.find(SearchInput).simulate('change', event);
    expect(spy).toHaveBeenCalled();
  });

  test('state updates with new filtered emojis on SearchInput change', () => {
    const event = {
      target: { value: 'smile' },
    };
    wrapper.find(SearchInput).simulate('change', event);
    const state = wrapper.instance().state;
    expect(state.filteredEmoji.length).toBeGreaterThan(0);
  });
});
