 Test generated by RoostGPT for test EmojiSearch using AI Type Open AI and AI Model gpt-4

import filterEmoji from "./filterEmoji";
import emojiList from "./emojiList.json";

describe('filterEmoji', () => {
  let emojiData;
  
  beforeAll(() => {
    emojiData = [...emojiList];
  });

  test('returns the correct emoji when a valid search term is input', () => {
    const searchTerm = 'smile';
    const filteredEmojis = filterEmoji(emojiData, searchTerm, 20);
    expect(filteredEmojis[0].title).toBe('Grinning Face With Big Eyes');
  });

  test('returns an empty array when an invalid search term is input', () => {
    const searchTerm = 'invalidSearchTerm';
    const filteredEmojis = filterEmoji(emojiData, searchTerm, 20);
    expect(filteredEmojis).toEqual([]);
  });

  test('limits the number of results according to the maxResults parameter', () => {
    const searchTerm = 'face';
    const maxResults = 5;
    const filteredEmojis = filterEmoji(emojiData, searchTerm, maxResults);
    expect(filteredEmojis).toHaveLength(maxResults);
  });
  
  test('returns all matching results when maxResults parameter is not provided', () => {
    const searchTerm = 'face';
    const filteredEmojis = filterEmoji(emojiData, searchTerm);
    expect(filteredEmojis.length).toBeGreaterThan(5);
  });
});
