 Test generated by RoostGPT for test EmojiSearch using AI Type Open AI and AI Model gpt-4

import React from 'react';
import { shallow } from 'enzyme';
import Header from './Header';

describe('Header Component', () => {
  let component;

  beforeEach(() => {
    component = shallow(<Header />);
  });

  test('It should render without errors', () => {
    const wrapper = component.find('.header');
    expect(wrapper.length).toBe(1);
  });

  test('It should render a logo', () => {
    const logo = component.find('.logo');
    expect(logo.length).toBe(1);
  });

  afterEach(() => {
    component.unmount();
  });
});
