 Test generated by RoostGPT for test EmojiSearch using AI Type Open AI and AI Model gpt-4

import React from 'react';
import { shallow } from 'enzyme';
import EmojiResultRow from './EmojiResultRow';

describe('EmojiResultRow', () => {
  let wrapper;

  beforeEach(() => {
    wrapper = shallow(<EmojiResultRow />);
  });

  test('renders without crashing', () => {
    expect(wrapper.exists()).toBe(true);
  });

  test('should have a div', () => {
    expect(wrapper.find('div').length).toBe(1);
  });

  test('should have a span', () => {
    expect(wrapper.find('span').length).toBe(1);
  });

  test('should have a p', () => {
    expect(wrapper.find('p').length).toBe(1);
  });

  test('should have a img', () => {
    expect(wrapper.find('img').length).toBe(1);
  });

  test('should have correct props for img', () => {
    wrapper = shallow(<EmojiResultRow title="smile" symbol="😀" />);
    expect(wrapper.find('img').props()).toEqual({
      alt: "smile",
      src: "😀",
      title: "smile"
    });
  });
});
