 Test generated by RoostGPT for test EmojiSearch using AI Type Open AI and AI Model gpt-4-1106-preview

import React from "react";
import ReactDOM from "react-dom";
import App from "./App";
import "./index.css";
import "github-fork-ribbon-css/gh-fork-ribbon.css";

ReactDOM.render(<App />, document.getElementById("root"));

