 Test generated by RoostGPT for test EmojiSearch using AI Type Open AI and AI Model gpt-4-1106-preview

import React, { PureComponent } from "react";
import PropTypes from "prop-types";
import "./SearchInput.css";

export default class SearchInput extends PureComponent {
  static propTypes = {
    textChange: PropTypes.func
  };

  handleChange = event => {
    this.props.textChange(event);
  };

  render() {
    return (
      <div className="component-search-input">
        <div>
          <input onChange={this.handleChange} />
        </div>
      </div>
    );
  }
}

