 Test generated by RoostGPT for test EmojiSearch using AI Type Open AI and AI Model gpt-4-1106-preview

import React from 'react';
import { render, fireEvent } from '@testing-library/react';
import SearchInput from './SearchInput';

describe('SearchInput component', () => {
  test('renders without crashing', () => {
    const { getByRole } = render(<SearchInput />);
    expect(getByRole('textbox')).toBeInTheDocument();
  });

  test('calls textChange prop on input change', () => {
    const textChangeMock = jest.fn();
    const { getByRole } = render(<SearchInput textChange={textChangeMock} />);
    fireEvent.change(getByRole('textbox'), { target: { value: 'test' } });
    expect(textChangeMock).toHaveBeenCalledTimes(1);
  });

  test('does not call textChange prop when not provided', () => {
    // This test verifies that the component does not break if textChange prop is not given
    const { getByRole } = render(<SearchInput />);
    expect(() => fireEvent.change(getByRole('textbox'), { target: { value: 'test' } })).not.toThrow();
  });

  // Add additional test cases for edge cases, different input values, etc.
});

